import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('it');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  it: {
    // Splash Screen
    'splash.title': 'yo_work',
    
    // Walkthrough
    'walkthrough.welcome.title': 'Benvenuto su yo_work',
    'walkthrough.welcome.description': 'La piattaforma che connette modelli, hostess e agenzie attraverso presentazioni video professionali.',
    'walkthrough.profile.title': 'Crea il tuo Profilo Video',
    'walkthrough.profile.description': 'Registra un video di presentazione di 30 secondi per mostrare la tua personalità e le tue competenze professionali.',
    'walkthrough.discover.title': 'Scopri Nuovi Talenti',
    'walkthrough.discover.description': 'Scorri i profili, guarda i video di presentazione e trova i professionisti perfetti per i tuoi progetti.',
    'walkthrough.connect.title': 'Connetti e Collabora',
    'walkthrough.connect.description': 'Quando c\'è un match, inizia a chattare e organizza collaborazioni professionali di successo.',
    'walkthrough.verified.title': 'Solo Professionisti Verificati',
    'walkthrough.verified.description': 'Tutti gli utenti sono verificati per garantire un ambiente sicuro e professionale per le tue collaborazioni.',
    'walkthrough.skip': 'Salta',
    'walkthrough.next': 'Avanti',
    'walkthrough.start': 'Inizia',
    
    // Onboarding
    'onboarding.title': 'Benvenuto su yo_work',
    'onboarding.subtitle': 'La piattaforma professionale che connette modelli, hostess e agenzie di marketing attraverso presentazioni video.',
    'onboarding.feature1.title': 'Profili Video',
    'onboarding.feature1.description': 'Video professionali di presentazione da 30 secondi',
    'onboarding.feature2.title': 'Matching Intelligente',
    'onboarding.feature2.description': 'Connetti agenzie e talenti in modo efficiente',
    'onboarding.feature3.title': 'Professionisti Verificati',
    'onboarding.feature3.description': 'Tutti gli utenti verificati solo per scopi professionali',
    'onboarding.startNow': 'Inizia Ora',
    'onboarding.haveAccount': 'Ho Già un Account',
    'onboarding.terms': 'yo_work è esclusivamente per scopi professionali. Continuando, accetti i nostri Termini di Servizio e l\'Informativa sulla Privacy.',
    
    // Auth
    'auth.login': 'Accedi',
    'auth.signUp': 'Registrati',
    'auth.title.1': 'Crea il tuo account professionale',
    'auth.title.2': 'Accedi al tuo account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Conferma Password',
    'auth.name': 'Nome Completo',
    'auth.fullName': 'Nome Completo',
    'auth.role': 'Ruolo',
    'auth.role.model': 'Modello/Hostess',
    'auth.role.agency': 'Agenzia',
    'auth.submit': 'Continua',
    'auth.back': 'Indietro',
    'auth.joinAs': 'Iscriviti come',
    'auth.selectRole': 'Seleziona un ruolo',
    'auth.term': 'Accetto i Termini di Servizio e l\'Informativa sulla Privacy, e confermo che questo account è esclusivamente per uso professionale.',
    'auth.create': 'Crea Account',
    'auth.continue': 'Continua',
    'auth.haveAccount': 'Hai già un account?',
    'auth.noAccount': 'Non hai un account?',
    'auth.signUpHere': 'Registrati qui',
    'auth.loginHere': 'Accedi qui',
    'auth.forgotPassword': 'Password dimenticata?',
    'auth.name.placeholder': 'Inserisci il tuo nome completo',
    'auth.email.placeholder': 'Inserisci la tua email',
    'auth.password.placeholder': 'Inserisci la tua password',
    
    // Profile Settings
    'settings.title': 'Profilo e Impostazioni',
    'settings.editProfile': 'Modifica Profilo',
    'settings.changePhoto': 'Cambia Foto',
    'settings.preferences': 'Preferenze',
    'settings.notifications': 'Notifiche',
    'settings.privacy': 'Privacy',
    'settings.help': 'Aiuto',
    'settings.logout': 'Logout',
    'settings.save': 'Salva Modifiche',
    'settings.upgradePro': 'Upgrade to Pro',
    'settings.alreadyPro': 'You are already a Pro',
    'settings.name': 'Nome',
    'settings.email': 'Email',
    'settings.age': 'Età',
    'settings.height': 'Altezza',
    'settings.location': 'Località',
    'settings.cardNumber': 'Numero Carta',
    'settings.professionalBio': 'Bio Professionale',
    'settings.saveChanges': 'Salva Modifiche',
    'settings.cancel': 'Annulla',
    'settings.professionalVideo': 'Video Professionale',
    'settings.professionalPresentation': 'Presentazione professionale di 30 secondi',
    'settings.uploadPresentationVideo': 'Carica un video di presentazione',
    'settings.uploadVideo': 'Carica Video',
    'settings.privacySettings': 'Impostazioni Privacy',
    'settings.termsOfService': 'Termini di Servizio',
    'settings.privacyPolicy': 'Informativa sulla Privacy',
    'settings.helpSupport': 'Aiuto e Supporto',
    'settings.disconnect': 'Disconnetti',
    'settings.appDescription': 'Piattaforma Professionale per il Matching di Talenti',
    'settings.profileUpdated': 'Profilo aggiornato con successo!',
    'settings.profileUpdateError': 'Errore nell\'aggiornamento del profilo',
    
    // Main Feed
    'feed.title': 'Feed Principale',
    'feed.profileCompleteness': 'Completezza Profilo',
    'feed.editProfile': 'Modifica Profilo',
    'feed.uploadPhotos': 'Carica Foto (Max {max})',
    'feed.jobsFeed': 'Feed Lavori',
    'feed.swipeMode': 'Modalità Swipe',
    'feed.listMode': 'Modalità Lista',
    'feed.noMore': 'Nessun profilo da mostrare!',
    'feed.location': 'da',
    'feed.viewProfile': 'Visualizza Profilo',
    
    // User Detail
    'user.profile': 'Profilo',
    'user.details': 'Dettagli',
    'user.age': 'Età',
    'user.height': 'Altezza',
    'user.category': 'Categoria',
    'user.location': 'Posizione',
    'user.bio': 'Biografia',
    'userDetail.about': 'Chi sono',
    'userDetail.gallery': 'Galleria',
    'userDetail.contact': 'Contatto',
    'userDetail.pass': 'Passa',
    'userDetail.like': 'Mi piace',
    'userDetail.loading': 'Caricamento dettagli modello...',
    'userDetail.modelNotFound': 'Modello non trovato.',
    'userDetail.back': 'Indietro',
    'userDetail.noVideoAvailable': 'Nessun video disponibile',
    'userDetail.portfolio': 'Portfolio',
    'userDetail.noPortfolioImages': 'Nessuna immagine del portfolio',
    'userDetail.addedToFavorites': 'Aggiunto ai preferiti',
    'userDetail.addToFavorites': 'Aggiungi ai preferiti',
    'userDetail.age': 'Età',
    'userDetail.height': 'Altezza',
    'userDetail.skills': 'Competenze',
    
    // Chat
    'chat.title': 'Chat',
    'chat.newMessage': 'Nuovo Messaggio',
    'chat.send': 'Invia',
    'chat.placeholder': 'Scrivi un messaggio...',
    'chat.typeMessage': 'Scrivi un messaggio...',
    'chat.noChats': 'Nessuna chat ancora',
    'chat.startMatching': 'Inizia a fare match per vedere le tue conversazioni qui!',
    'chat.loading': 'Caricamento...',
    'chat.online': 'Online ora',
    
    // Campaign Detail
    'campaign.apply': 'Candidati',
    'campaign.back': 'Indietro',
    'campaign.timeLeft': 'Tempo Rimanente',
    'campaign.requirements': 'Requisiti',
    'campaign.budget': 'Budget',
    'campaign.description': 'Descrizione',
    
    // Match Screen
    'match.title': 'Match!',
    'match.oops': 'Ops!',
    'match.score': 'Punteggio Match',
    'match.startChat': 'Inizia Chat',
    'match.continueExploring': 'Continua Esplorando',
    'match.greatMatch': 'Ottimo Match!',
    'match.noMatch': 'Nessun Match',
    'match.matchDescription': 'Sembrate fatti l\'uno per l\'altro!',
    'match.noMatchDescription': 'Non c\'è stata una corrispondenza questa volta.',
    'match.subtitle': 'Ottimo! Vi piacete entrambi. Inizia una conversazione ora.',
    'match.sendMessage': 'Invia un Messaggio',
    'match.keepSwiping': 'Continua a Scorrere',
    
    // Search
    'search.title': 'Cerca',
    'search.placeholder': 'Cerca modelli, hostess...',
    'search.filters': 'Filtri',
    'search.all': 'Tutti',
    'search.model': 'Modello',
    'search.hostess': 'Hostess',
    'search.agency': 'Agenzia',
    'search.recent': 'Ricerche recenti',
    'search.noResults': 'Nessun risultato trovato',
    'search.tryDifferent': 'Prova termini di ricerca diversi',
    'search.models': 'Modelle',
    'search.photographer': 'Fotografo',
    'search.other': 'Altro',
    'search.loading': 'Caricamento...',
    'search.view': 'Visualizza',
    
    // 404 Page
    'notFound.title': '404',
    'notFound.message': 'Ops! Pagina non trovata',
    'notFound.returnHome': 'Torna alla Home',
    
    // Navigation
    'nav.feed': 'Feed',
    'nav.search': 'Cerca',
    'nav.campaigns': 'Campagne',
    'nav.chat': 'Chat',
    'nav.profile': 'Profilo',
    
    // Language
    'language.select': 'Seleziona Lingua',
    'language.italian': 'Italiano',
    'language.english': 'English',
    
    // Profile Creation
    "Page.title": "Crea Profilo",
    "page.subtitle": "Costruisci il tuo profilo professionale per iniziare a connetterti.",
    "page.info": "Informazioni Base",
    "profile-creation.name": "Nome Completo",
    "profile-creation.name.placeholder": "Il tuo nome professionale",
    "profile-creation.age": "Età",
    "profile-creation.height": "Altezza",
    "profile-creation.gender": "Genere",
    "profile-creation.gender.select": "Seleziona genere",
    "profile-creation.gender.male": "Maschio",
    "profile-creation.gender.female": "Femmina",
    "profile-creation.gender.other": "Non-binario",
    "profile-creation.gender.agnecy": "Agenzia",
    "profile-creation.location": "Posizione",
    "profile-creation.bio": "Bio Professionale",
    "profile-creation.bio.placeholder": "Breve descrizione della tua esperienza e specializzazioni...",
    "profile-creation.video": "Video Professionale (Richiesto)",
    "profile-creation.record": "Carica il tuo video di presentazione",
    "profile-creation.video.length": "Massimo 30 secondi • Supportato MP4, MOV",
    "profile-creation.record.button": "Scegli File Video",
    "profile-creation.record.info": "Il tuo video dovrebbe mostrare professionalmente il tuo aspetto, personalità e capacità comunicative. Mantienilo appropriato per il business e coinvolgente.",
    "profile-creation.complete": "Completa Configurazione Profilo",
    'profile-creation.category': 'Categoria',
    'profile-creation.category.select': 'Seleziona una categoria',
    'profile-creation.category.hostess': 'Hostess',
    'profile-creation.category.model': 'Modello',
    'profile-creation.category.photographer': 'Fotografo',
    'profile-creation.category.promotar': 'Promoter',
    'profile-creation.category.waiter': 'Cameriere',
    'profile-creation.category.other': 'Altro',
    
    // Profile Creation Agency
    'profile-creation.agency.name': "Nome Agenzia",
    'profile-creation.agency.name.placeholder': "Il nome completo della tua agenzia",
    'profile-creation.years': "Anni di Attività",
    'profile-creation.employee': "Numero di Dipendenti",
    'profile-creation.agency.website': "Piattaforma Social Media",
    'profile-creation.agency.website.placeholder': "Link al tuo account",
    
    // Campaigns
    'campaigns.title': 'Campagne',
    'campaigns.create': 'Crea Campagna',
    'campaigns.edit': 'Modifica Campagna',
    'campaigns.name': 'Nome Campagna',
    'campaigns.description': 'Descrizione',
    'campaigns.requirements': 'Requisiti',
    'campaigns.save': 'Salva Campagna',
    'campaigns.active': 'Attive',
    'campaigns.completed': 'Completate',
    'campaigns.noActive': 'Nessuna campagna attiva',
    'campaigns.startCreating': 'Inizia a creare campagne per gestire i tuoi progetti!',
    'campaigns.details': 'Dettagli Campagna',
    'campaigns.participants': 'Partecipanti',
    'campaigns.status': 'Stato',
    'campaigns.budget': 'Budget',
    'campaigns.deadline': 'Scadenza',
    'campaigns.apply': 'Candidati',
    'campaigns.loading': 'Caricamento campagne...',
    'campaigns.createdSuccessfully': 'Campagna creata con successo!',
    'campaigns.creationError': 'Errore nella creazione della campagna',
    'campaigns.titlePlaceholder': 'Fashion Week Estate 2024',
    'campaigns.descriptionPlaceholder': 'Descrivi i requisiti della tua campagna...',
    'campaigns.startTime': 'Orario Inizio',
    'campaigns.endTime': 'Orario Fine',
    'campaigns.city': 'Città',
    'campaigns.address': 'Indirizzo',
    'campaigns.addressPlaceholder': 'Via, CAP, Italia',
    'campaigns.compensation': 'Compenso (€)',
    'campaigns.requiredPeople': 'Numero Persone Richieste',
    'campaigns.proOnly': 'Solo profili Pro',
    'campaigns.creating': 'Creazione in corso...',
    'campaigns.searchPlaceholder': 'Cerca campagne...',
    'campaigns.updatedSuccessfully': 'Campagna aggiornata con successo!',
    'campaigns.updateError': 'Errore nella modifica della campagna',
    
    // Model Feed Screen
    'modelFeed.welcomeBack': 'Bentornato',
    'modelFeed.profileCompleteness': 'Completezza del profilo',
    'modelFeed.profilePhoto': 'Foto del profilo',
    'modelFeed.age': 'Età',
    'modelFeed.height': 'Altezza',
    'modelFeed.measurements': 'Misure',
    'modelFeed.introVideo': 'Video di presentazione di 30s',
    'modelFeed.categorySelected': 'Categoria selezionata',
    'modelFeed.editProfile': 'Modifica profilo',
    'modelFeed.availableJobs': 'Lavori disponibili',
    'modelFeed.list': 'Lista',
    'modelFeed.swipe': 'Scorri',
    'modelFeed.daysLeft': 'giorni rimasti',
    'modelFeed.today': 'Oggi',
    'modelFeed.expired': 'Scaduto',
    'modelFeed.genderAny': 'Qualsiasi',
    'modelFeed.genderWomen': 'Femminile',
    'modelFeed.genderMen': 'Maschile',
    'modelFeed.start': 'Inizio',
    'modelFeed.end': 'Fine',
    'modelFeed.deadline': 'Scadenza',
    'modelFeed.applicants': 'candidati',
    'modelFeed.apply': 'Candidati',
    'modelFeed.pass': 'Passa',
    'modelFeed.noMoreJobs': 'Nessun altro lavoro. Ricontrolla più tardi.',
    'modelFeed.rateAgency': 'Valuta Agenzia',
    'modelFeed.howWasJob': 'Come è andato il tuo ultimo lavoro con',
    'modelFeed.submitRating': 'Invia valutazione',
    'modelFeed.jobSkipped': 'Lavoro saltato',
    'modelFeed.youSkippedJob': 'Hai saltato il lavoro',
    'modelFeed.pleaseLogin': 'Effettua l\'accesso per caricare le foto.',
    'modelFeed.unknownAgency': 'Agenzia Sconosciuta',
    'modelFeed.categoryModel': 'Modello',
    'modelFeed.defaultCity': 'Milano, IT',
    'modelFeed.openVideoUploader': 'Apri caricatore video verticale di 30s',
    'modelFeed.untitled': 'Senza Titolo',
    'modelFeed.open': 'Aperto',
    'modelFeed.noDescription': '—',
    'modelFeed.noLocation': '—',
    
    // Campaign Detail Screen
    'campaignDetail.title': 'Dettagli Campagna',
    'campaignDetail.budget': 'Budget',
    'campaignDetail.applicants': 'Candidati',
    'campaignDetail.deadline': 'Scadenza Candidature',
    'campaignDetail.description': 'Descrizione Campagna',
    'campaignDetail.whatWeLookFor': 'Cosa cerchiamo:',
    'campaignDetail.requirements': 'Requisiti',
    'campaignDetail.startDate': 'Data di Inizio',
    'campaignDetail.endDate': 'Data di Fine',
    'campaignDetail.gender': 'Genere',
    'campaignDetail.location': 'Località',
    'campaignDetail.apply': 'Candidati per questa Campagna',
    'campaignDetail.reviewTime': 'La tua candidatura sarà revisionata entro 24-48 ore',
    
    // Search Screen (duplicate removed - keeping the first occurrence)
    
    // User Detail Screen (duplicate removed - keeping the first occurrence)
    
    // Match Confirmation Screen (duplicate removed - keeping the first occurrence)
    
    // Profile Creation Screen Model
    'profileCreation.profileSaved': 'Profilo salvato!',
    'profileCreation.errorSaving': 'Errore nel salvare il profilo',
    'profileCreation.fileSizeExceeds': 'La dimensione del file supera il limite di 30MB',
    'profileCreation.mustBeLoggedIn': 'Devi essere loggato per caricare un video',
    'profileCreation.videoUploadFailed': 'Caricamento video fallito',
    
    // Photo Uploader
    'photoUploader.title': 'Carica Foto',
    'photoUploader.select': 'Seleziona',
    'photoUploader.upload': 'Carica',
    'photoUploader.uploading': 'Caricamento...',
    'photoUploader.uploadedPhotos': 'Foto Caricate:',
    'photoUploader.maxLimitReached': 'Limite massimo raggiunto. Puoi caricare solo fino a',
    'photoUploader.photos': 'foto',
    'photoUploader.maxLimitReachedSimple': 'Limite massimo raggiunto.',
    'photoUploader.uploadFailed': 'Caricamento fallito.',
    'photoUploader.upgradeToPro': ' Passa a Pro per fino a 10 foto.',
    
    // Agency Feed Screen
    'agencyFeed.all': 'Tutti',
    'agencyFeed.models': 'Modelle',
    'agencyFeed.hostess': 'Hostess',
    'agencyFeed.photographer': 'Fotografo',
    'agencyFeed.pendingApproval': 'In Attesa di Approvazione',
    'agencyFeed.loadingProfiles': 'Caricamento profili...',
    'agencyFeed.noProfilesAvailable': 'Nessun profilo disponibile',
    'agencyFeed.discover': 'scopri',
    'agencyFeed.liked': 'Mi piace!',
    
    // Agency Profile
    'agencyProfile.additionalInfo': 'Informazioni Aggiuntive',
    'agencyProfile.vatNumber': 'Numero Partita IVA',
    'agencyProfile.vatNumberPlaceholder': 'IT12345678901',
    'agencyProfile.vatNumberOptional': 'Opzionale',
    'agencyProfile.companyDocuments': 'Documenti Aziendali',
    'agencyProfile.uploadPdf': 'Carica Documento PDF',
    'agencyProfile.pdfDescription': 'Carica certificati, licenze o altri documenti aziendali',
    'agencyProfile.selectPdf': 'Seleziona PDF',
    'agencyProfile.pdfOptional': 'Opzionale',
    'agencyProfile.pdfUploaded': 'PDF caricato con successo',
    'agencyProfile.replacePdf': 'Sostituisci PDF',
    'agencyProfile.removePdf': 'Rimuovi PDF',
    'agencyProfile.uploadingPdf': 'Caricamento PDF...',
    'agencyProfile.invalidFileType': 'Seleziona solo file PDF',
    'agencyProfile.existingPdf': 'PDF esistente',
    'agencyProfile.pdfAlreadyUploaded': 'PDF già caricato',
  },
  en: {
    // Splash Screen
    'splash.title': 'yo_work',
    
    // Walkthrough
    'walkthrough.welcome.title': 'Welcome to yo_work',
    'walkthrough.welcome.description': 'The platform that connects models, hostesses and agencies through professional video presentations.',
    'walkthrough.profile.title': 'Create Your Video Profile',
    'walkthrough.profile.description': 'Record a 30-second presentation video to showcase your personality and professional skills.',
    'walkthrough.discover.title': 'Discover New Talents',
    'walkthrough.discover.description': 'Swipe through profiles, watch presentation videos and find the perfect professionals for your projects.',
    'walkthrough.connect.title': 'Connect and Collaborate',
    'walkthrough.connect.description': 'When there\'s a match, start chatting and organize successful professional collaborations.',
    'walkthrough.verified.title': 'Verified Professionals Only',
    'walkthrough.verified.description': 'All users are verified to ensure a safe and professional environment for your collaborations.',
    'walkthrough.skip': 'Skip',
    'walkthrough.next': 'Next',
    'walkthrough.start': 'Start',
    
    // Onboarding
    'onboarding.title': 'Welcome to yo_work',
    'onboarding.subtitle': 'The professional platform that connects models, hostesses and marketing agencies through video presentations.',
    'onboarding.feature1.title': 'Video Profiles',
    'onboarding.feature1.description': 'Professional 30-second presentation videos',
    'onboarding.feature2.title': 'Smart Matching',
    'onboarding.feature2.description': 'Connect agencies and talents efficiently',
    'onboarding.feature3.title': 'Verified Professionals',
    'onboarding.feature3.description': 'All users verified for professional purposes only',
    'onboarding.startNow': 'Start Now',
    'onboarding.haveAccount': 'I Already Have an Account',
    'onboarding.terms': 'yo_work is exclusively for professional purposes. By continuing, you agree to our Terms of Service and Privacy Policy.',
    
    // Auth
    'auth.login': 'Login',
    'auth.signUp': 'Sign Up',
    'auth.title.1': 'Create your professional account',
    'auth.title.2': 'Login to your account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Full Name',
    'auth.fullName': 'Full Name',
    'auth.role': 'Role',
    'auth.role.model': 'Model/Hostess',
    'auth.role.agency': 'Agency',
    'auth.submit': 'Continue',
    'auth.back': 'Back',
    'auth.joinAs': 'Join as',
    'auth.selectRole': 'Select a role',
    'auth.term': 'I accept the Terms of Service and Privacy Policy, and confirm that this account is for professional use only.',
    'auth.create': 'Create Account',
    'auth.continue': 'Continue',
    'auth.haveAccount': 'Already have an account?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.signUpHere': 'Sign up here',
    'auth.loginHere': 'Login here',
    'auth.forgotPassword': 'Forgot password?',
    'auth.name.placeholder': 'Enter your full name',
    'auth.email.placeholder': 'Enter your email address',
    'auth.password.placeholder': 'Enter your password',
    
    // Profile Settings
    'settings.title': 'Profile and Settings',
    'settings.editProfile': 'Edit Profile',
    'settings.changePhoto': 'Change Photo',
    'settings.preferences': 'Preferences',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.help': 'Help',
    'settings.logout': 'Logout',
    'settings.save': 'Save Changes',
    'settings.upgradePro': 'Upgrade to Pro',
    'settings.alreadyPro': 'You are already a Pro',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.age': 'Age',
    'settings.height': 'Height',
    'settings.location': 'Location',
    'settings.cardNumber': 'Card Number',
    'settings.professionalBio': 'Professional Bio',
    'settings.saveChanges': 'Save Changes',
    'settings.cancel': 'Cancel',
    'settings.professionalVideo': 'Professional Video',
    'settings.professionalPresentation': 'Professional 30-second presentation',
    'settings.uploadPresentationVideo': 'Upload a presentation video',
    'settings.uploadVideo': 'Upload Video',
    'settings.privacySettings': 'Privacy Settings',
    'settings.termsOfService': 'Terms of Service',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.helpSupport': 'Help & Support',
    'settings.disconnect': 'Disconnect',
    'settings.appDescription': 'Professional Platform for Talent Matching',
    'settings.profileUpdated': 'Profile updated successfully!',
    'settings.profileUpdateError': 'Error updating profile',
    
    // Main Feed
    'feed.title': 'Main Feed',
    'feed.profileCompleteness': 'Profile Completeness',
    'feed.editProfile': 'Edit Profile',
    'feed.uploadPhotos': 'Upload Photos (Max {max})',
    'feed.jobsFeed': 'Jobs Feed',
    'feed.swipeMode': 'Swipe Mode',
    'feed.listMode': 'List Mode',
    'feed.noMore': 'No more profiles to show!',
    'feed.location': 'from',
    'feed.viewProfile': 'View Profile',
    
    // User Detail
    'user.profile': 'Profile',
    'user.details': 'Details',
    'user.age': 'Age',
    'user.height': 'Height',
    'user.category': 'Category',
    'user.location': 'Location',
    'user.bio': 'Bio',
    'userDetail.about': 'About',
    'userDetail.gallery': 'Gallery',
    'userDetail.contact': 'Contact',
    'userDetail.pass': 'Pass',
    'userDetail.like': 'Like',
    'userDetail.loading': 'Loading model details...',
    'userDetail.modelNotFound': 'Model not found.',
    'userDetail.back': 'Back',
    'userDetail.noVideoAvailable': 'No video available',
    'userDetail.portfolio': 'Portfolio',
    'userDetail.noPortfolioImages': 'No portfolio images',
    'userDetail.addedToFavorites': 'Added to favorites',
    'userDetail.addToFavorites': 'Add to favorites',
    'userDetail.age': 'Age',
    'userDetail.height': 'Height',
    'userDetail.skills': 'Skills',
    
    // Chat
    'chat.title': 'Chat',
    'chat.newMessage': 'New Message',
    'chat.send': 'Send',
    'chat.placeholder': 'Write a message...',
    'chat.typeMessage': 'Type a message...',
    'chat.noChats': 'No chats yet',
    'chat.startMatching': 'Start matching to see your conversations here!',
    'chat.loading': 'Loading...',
    'chat.online': 'Online now',
    
    // Campaign Detail
    'campaign.apply': 'Apply',
    'campaign.back': 'Back',
    'campaign.timeLeft': 'Time Left',
    'campaign.requirements': 'Requirements',
    'campaign.budget': 'Budget',
    'campaign.description': 'Description',
    
    // Match Screen
    'match.title': 'Match!',
    'match.oops': 'Oops!',
    'match.score': 'Match Score',
    'match.startChat': 'Start Chat',
    'match.continueExploring': 'Continue Exploring',
    'match.greatMatch': 'Great Match!',
    'match.noMatch': 'No Match',
    'match.matchDescription': 'You seem perfect for each other!',
    'match.noMatchDescription': 'There was no match this time.',
    'match.subtitle': 'Great! You both like each other. Start a conversation now.',
    'match.sendMessage': 'Send a Message',
    'match.keepSwiping': 'Keep Swiping',
    
    // Search
    'search.title': 'Search',
    'search.placeholder': 'Search by name, role or city...',
    'search.filters': 'Filters',
    'search.all': 'All',
    'search.model': 'Model',
    'search.hostess': 'Hostess',
    'search.agency': 'Agency',
    'search.recent': 'Recent searches',
    'search.noResults': 'No results found',
    'search.tryDifferent': 'Try different search terms',
    'search.models': 'Models',
    'search.photographer': 'Photographer',
    'search.other': 'Other',
    'search.loading': 'Loading...',
    'search.view': 'View',
    
    // 404 Page
    'notFound.title': '404',
    'notFound.message': 'Oops! Page not found',
    'notFound.returnHome': 'Return to Home',
    
    // Navigation
    'nav.feed': 'Feed',
    'nav.search': 'Search',
    'nav.campaigns': 'Campaigns',
    'nav.chat': 'Chat',
    'nav.profile': 'Profile',
    
    // Language
    'language.select': 'Select Language',
    'language.italian': 'Italiano',
    'language.english': 'English',
    
    // Profile Creation
    "Page.title": "Create Profile",
    "page.subtitle": "Build your professional profile to start connecting.",
    "page.info": "Basic Information",
    "profile-creation.name": "Full Name",
    "profile-creation.name.placeholder": "Your professional name",
    "profile-creation.age": "Age",
    "profile-creation.height": "Height",
    "profile-creation.gender": "Gender",
    "profile-creation.gender.select": "Select gender",
    "profile-creation.gender.male": "Male",
    "profile-creation.gender.female": "Female",
    "profile-creation.gender.other": "Non-binary",
    "profile-creation.gender.agnecy": "Agency",
    "profile-creation.location": "Location",
    "profile-creation.bio": "Professional Bio",
    "profile-creation.bio.placeholder": "Brief description of your experience and specialties...",
    "profile-creation.video": "Professional Video (Required)",
    "profile-creation.record": "Upload your introduction video",
    "profile-creation.video.length": "Maximum 30 seconds • Supported MP4, MOV",
    "profile-creation.record.button": "Choose Video File",
    "profile-creation.record.info": "Your video should professionally showcase your appearance, personality, and communication skills. Keep it business-appropriate and engaging.",
    "profile-creation.complete": "Complete Profile Setup",
    'profile-creation.category': 'Category',
    'profile-creation.category.select': 'Select a category',
    'profile-creation.category.hostess': 'Hostess',
    'profile-creation.category.model': 'Model',
    'profile-creation.category.photographer': 'Photographer',
    'profile-creation.category.promotar': 'Promoter',
    'profile-creation.category.waiter': 'Waiter',
    'profile-creation.category.other': 'Other',
    
    // Profile Creation Agency
    'profile-creation.agency.name': "Agency Name",
    'profile-creation.agency.name.placeholder': "The full name of your agency",
    'profile-creation.years': "Years of Operation",
    'profile-creation.employee': "Number of Employees",
    'profile-creation.agency.website': "Social Media Platform",
    'profile-creation.agency.website.placeholder': "Link to your account",    
    
    // Campaigns
    'campaigns.title': 'Campaigns',
    'campaigns.create': 'Create Campaign',
    'campaigns.edit': 'Edit Campaign',
    'campaigns.name': 'Campaign Name',
    'campaigns.description': 'Description',
    'campaigns.requirements': 'Requirements',
    'campaigns.save': 'Save Campaign',
    'campaigns.active': 'Active',
    'campaigns.completed': 'Completed',
    'campaigns.noActive': 'No active campaigns',
    'campaigns.startCreating': 'Start creating campaigns to manage your projects!',
    'campaigns.details': 'Campaign Details',
    'campaigns.participants': 'Participants',
    'campaigns.status': 'Status',
    'campaigns.budget': 'Budget',
    'campaigns.deadline': 'Deadline',
    'campaigns.apply': 'Apply',
    'campaigns.loading': 'Loading campaigns...',
    'campaigns.createdSuccessfully': 'Campaign created successfully!',
    'campaigns.creationError': 'Error creating campaign',
    'campaigns.titlePlaceholder': 'Summer Fashion Week 2024',
    'campaigns.descriptionPlaceholder': 'Describe your campaign requirements...',
    'campaigns.startTime': 'Start Time',
    'campaigns.endTime': 'End Time',
    'campaigns.city': 'City',
    'campaigns.address': 'Address',
    'campaigns.addressPlaceholder': 'Street, ZIP, Country',
    'campaigns.compensation': 'Compensation (€)',
    'campaigns.requiredPeople': 'Required People',
    'campaigns.proOnly': 'Pro profiles only',
    'campaigns.creating': 'Creating...',
    'campaigns.searchPlaceholder': 'Search campaigns...',
    'campaigns.updatedSuccessfully': 'Campaign updated successfully!',
    'campaigns.updateError': 'Error updating campaign',
    
    // Model Feed Screen
    'modelFeed.welcomeBack': 'Welcome back',
    'modelFeed.profileCompleteness': 'Profile completeness',
    'modelFeed.profilePhoto': 'Profile photo',
    'modelFeed.age': 'Age',
    'modelFeed.height': 'Height',
    'modelFeed.measurements': 'Measurements',
    'modelFeed.introVideo': '30s intro video',
    'modelFeed.categorySelected': 'Category selected',
    'modelFeed.editProfile': 'Edit profile',
    'modelFeed.availableJobs': 'Available Jobs',
    'modelFeed.list': 'List',
    'modelFeed.swipe': 'Swipe',
    'modelFeed.daysLeft': 'days left',
    'modelFeed.today': 'Today',
    'modelFeed.expired': 'Expired',
    'modelFeed.genderAny': 'Any',
    'modelFeed.genderWomen': 'Women',
    'modelFeed.genderMen': 'Men',
    'modelFeed.start': 'Start',
    'modelFeed.end': 'End',
    'modelFeed.deadline': 'Deadline',
    'modelFeed.applicants': 'applicants',
    'modelFeed.apply': 'Apply',
    'modelFeed.pass': 'Pass',
    'modelFeed.noMoreJobs': 'No more jobs. Check back later.',
    'modelFeed.rateAgency': 'Rate Agency',
    'modelFeed.howWasJob': 'How was your last job with',
    'modelFeed.submitRating': 'Submit rating',
    'modelFeed.jobSkipped': 'Job skipped',
    'modelFeed.youSkippedJob': 'You skipped job',
    'modelFeed.pleaseLogin': 'Please log in to upload photos.',
    'modelFeed.unknownAgency': 'Unknown Agency',
    'modelFeed.categoryModel': 'Model',
    'modelFeed.defaultCity': 'Milan, IT',
    'modelFeed.openVideoUploader': 'Open 30s vertical video uploader',
    'modelFeed.untitled': 'Untitled',
    'modelFeed.open': 'Open',
    'modelFeed.noDescription': '—',
    'modelFeed.noLocation': '—',
    
    // Campaign Detail Screen
    'campaignDetail.title': 'Campaign Details',
    'campaignDetail.budget': 'Budget',
    'campaignDetail.applicants': 'Applicants',
    'campaignDetail.deadline': 'Application Deadline',
    'campaignDetail.description': 'Campaign Description',
    'campaignDetail.whatWeLookFor': 'What we are looking for:',
    'campaignDetail.requirements': 'Requirements',
    'campaignDetail.startDate': 'Start Date',
    'campaignDetail.endDate': 'End Date',
    'campaignDetail.gender': 'Gender',
    'campaignDetail.location': 'Location',
    'campaignDetail.apply': 'Apply for this Campaign',
    'campaignDetail.reviewTime': 'Your application will be reviewed within 24-48 hours',
    
    // Search Screen (duplicate removed - keeping the first occurrence)
    
    // User Detail Screen (duplicate removed - keeping the first occurrence)
    
    // Match Confirmation Screen (duplicate removed - keeping the first occurrence)
    
    // Profile Creation Screen Model
    'profileCreation.profileSaved': 'Profile saved!',
    'profileCreation.errorSaving': 'Error saving profile',
    'profileCreation.fileSizeExceeds': 'File size exceeds 30MB limit',
    'profileCreation.mustBeLoggedIn': 'You must be logged in to upload a video',
    'profileCreation.videoUploadFailed': 'Video upload failed',
    
    // Photo Uploader
    'photoUploader.title': 'Upload Photos',
    'photoUploader.select': 'Select',
    'photoUploader.upload': 'Upload',
    'photoUploader.uploading': 'Uploading...',
    'photoUploader.uploadedPhotos': 'Uploaded Photos:',
    'photoUploader.maxLimitReached': 'Max limit reached. You can only upload up to',
    'photoUploader.photos': 'photos',
    'photoUploader.maxLimitReachedSimple': 'Max limit reached.',
    'photoUploader.uploadFailed': 'Upload failed.',
    'photoUploader.upgradeToPro': ' Upgrade to Pro for up to 10 photos.',
    
    // Agency Feed Screen
    'agencyFeed.all': 'All',
    'agencyFeed.models': 'Models',
    'agencyFeed.hostess': 'Hostess',
    'agencyFeed.photographer': 'Photographer',
    'agencyFeed.pendingApproval': 'Pending Approval',
    'agencyFeed.loadingProfiles': 'Loading profiles...',
    'agencyFeed.noProfilesAvailable': 'No profiles available',
    'agencyFeed.discover': 'discover',
    'agencyFeed.liked': 'Liked!',
    
    // Agency Profile
    'agencyProfile.additionalInfo': 'Additional Information',
    'agencyProfile.vatNumber': 'VAT Number',
    'agencyProfile.vatNumberPlaceholder': 'IT12345678901',
    'agencyProfile.vatNumberOptional': 'Optional',
    'agencyProfile.companyDocuments': 'Company Documents',
    'agencyProfile.uploadPdf': 'Upload PDF Document',
    'agencyProfile.pdfDescription': 'Upload certificates, licenses or other company documents',
    'agencyProfile.selectPdf': 'Select PDF',
    'agencyProfile.pdfOptional': 'Optional',
    'agencyProfile.pdfUploaded': 'PDF uploaded successfully',
    'agencyProfile.replacePdf': 'Replace PDF',
    'agencyProfile.removePdf': 'Remove PDF',
    'agencyProfile.uploadingPdf': 'Uploading PDF...',
    'agencyProfile.invalidFileType': 'Please select only PDF files',
    'agencyProfile.existingPdf': 'Existing PDF',
    'agencyProfile.pdfAlreadyUploaded': 'PDF already uploaded',
  }
};
